seed: 0
dt: 0.10
total_time: 100
num_update_steps: 200
decoupled_mode: true
num_chasers: 1

orbit:
  mu: 3.986004418e14
  semi_major_axis: 6678136.3
  eccentricity: 0.0
  t_periapsis: 0.0
  initial_conditions: [-50.0, 10.0, 5.0, 0.05, -0.01, 0.01]

mpc:
  horizon_steps:
    rendezvous: 80
    docking: 40
  actuation_steps:
    rendezvous: 20
    docking: 2
  state_bounds:
    - {lower: "-Inf", upper: "+Inf"}
    - {lower: "-Inf", upper: "+Inf"}
    - {lower: "-Inf", upper: "+Inf"}
    - {lower: "-Inf", upper: "+Inf"}
    - {lower: "-Inf", upper: "+Inf"}
    - {lower: "-Inf", upper: "+Inf"}
  input_bounds:
    - {lower: -0.1, upper: 0.1}
    - {lower: -0.1, upper: 0.1}
    - {lower: -0.1, upper: 0.1}
  Q: [1, 1, 1, 1, 1, 1]
  R: [0.0001, 0.0001, 0.0001]
  force_bounds:
    - {lower: -7000.0, upper: 7000.0}
    - {lower: -7000.0, upper: 7000.0}
    - {lower: -7000.0, upper: 7000.0}
  goal_bounds: [425.0, 475.0]

target:
  initial_orientation: [0.0, 0.2, -0.1]
  initial_angular_velocity: [-0.04, 0.1, -0.02]
  inertia:
    - [800.0, 2.0, 5.0]
    - [4.0, 450.0, 3.0]
    - [6.0, 8.0, 200.0]
  shape: "cylinder"
  center: [0.0, 0.0, 0.0]
  limits:
    l_T: 0.6
    r_T: 0.8
    tolerance: 0.001
  stop_time: 5.0
  discretize_dockers: true
  tolerance: 0.001
  observation_error:
    ang_pos: 4.0e-8
    ang_vel: 4.0e-8

tube:
  run_tube: true
  bandwidth_0: [0.25, 0.25, 0.25]
  boundary_layer_0: [0.5, 0.5, 0.5]
  convergence_rate: [0.1, 0.1, 0.1]
  sliding_gains: [60.0, 60.0, 60.0]
  bandwidth_range:
    lower: 0.01
    upper: 10.0
